### ISSUE TITLE
Adafruit bonnet issue with raspberry pi-4 POE connector

### ISSUE THREAD

**Issue by reinierdevl** [adafruit/Adafruit-RGB-Matrix-Bonnet-PCB#1]
The POE connector of the pi-4 touches the bonnet causuing short-circuits and does not allow the bonnet to be seated well. This is very clear when you solder the connector on the bonnet to acces remaining pins (like I did), but also without that it may touch the bonnet on the solderspots of the bonnet connector.

![IMG_20210128_163551246](https://user-images.githubusercontent.com/33804296/106306078-d336da00-625d-11eb-8851-b0579d65db5c.jpg)

**Comment by ladyada** [comment]
yeah its very annoying - this bonnet came out before the poe. use a lifter!
https://www.adafruit.com/product/4079

**Comment by reinierdevl** [comment]
where in the netherlands can I buy this, I find no-one selling them and getting them from your site will bring an insane17euro shipping costs
