### ISSUE TITLE
Minor hardware suggestions

### ISSUE THREAD

**Issue by marekm72** [adafruit/Adafruit-RGB-Matrix-Bonnet-PCB#3]
I'd like to suggest minor hardware design changes to allow separate +5V power supply for the LED matrix without power sequencing requirements.  Planning to drive the matrix (32x32, 1:8 scan) from the CM4IO board which has onboard +12V to +5V buck converter for the CM4 - but it has not enough power for the matrix, which will be powered separately.  So the LED matrix should be powered up before the RPi, otherwise the logic high outputs of the bonnet are clamped by the plain old 74HC logic to the matrix Vcc.

Unlike plain old 74HC, the 74AHCT logic chips in the hat/bonnet accept 3.3V input levels ('T' stands for TTL) and also input voltages higher than power supply ('A' - no clamping of high inputs to Vcc even at 0V).  But the '245 is bi-directional (here unnecessarily) and high-Z I/O pins don't have this capability (only purely input pins do), so I'd suggest to use the uni-directional 74AHCT541 instead, and power it from the same +5V power supply as the LED matrix (separate from the RPi +5V).  This way both power supplies can go up/down in any order.

While you're at it, I'd suggest adding a another (solder) jumper on the D row select pin as well - 1:8 scan matrix only has A, B, C and the one I have has D grounded.  So it is better to disconnect that pin to avoid a short-circuit if driven high by the GPIO.

About the higher quality option (use PWM for matrix BLANK, no sound) - do both GPIO4 and GPIO18 need to be shorted, or is it OK to just use GPIO18 only (PWM) and free up GPIO4 for other use?

**Comment by ladyada** [comment]
thanx!
